---
- name: Install necessary libraries
  become: True
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - libxinerama
    - make

- name: Checkout Suckless dwm code
  ansible.builtin.git:
    repo: "{{ dwm_custom_repo }}"
    dest: /home/{{ user_name }}/.local/share/suckless/dwm

- name: Build dwm
  become: True
  community.general.make:
    chdir: /home/{{ user_name }}/.local/share/suckless/dwm
    target: install

- name: Checkout Suckless dmenu code
  ansible.builtin.git:
    repo: "{{ dmenu_custom_repo }}"
    dest: /home/{{ user_name }}/.local/share/suckless/dmenu

- name: Build dmenu
  become: True
  make:
    chdir: /home/{{ user_name }}/.local/share/suckless/dmenu
    target: install

- name: Checkout Suckless st code
  ansible.builtin.git:
    repo: "{{ st_custom_repo }}"
    dest: /home/{{ user_name }}/.local/share/suckless/st

- name: Build st
  become: True
  make:
    chdir: /home/{{ user_name }}/.local/share/suckless/st
    target: install
  
- name: Checkout dwmblocks code
  ansible.builtin.git:
    repo: "{{ dwmblocks_custom_repo }}"
    dest: /home/{{ user_name }}/.local/share/suckless/dwmblocks

- name: Build dwmblocks
  become: True
  make:
    chdir: /home/{{ user_name }}/.local/share/suckless/dwmblocks
    target: install