---
- name: Pre-requisites for yay AUR Helper
  when: ansible_facts['os_family'] == 'Artix Linux'
  become: True
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - base-devel
    - git

- name: Install common libraries & utilities
  become: True
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ common_packages }}"
